### ISSUE TITLE
Error!!

### ISSUE THREAD

**Issue by Matetv** [xxxstasiek/stasiek_selldrugs#12]
Error running system event handling function for resource stasiek_selldrugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/locale.lua:10: attempt to concatenate a nil value (local 'str')
stack traceback:
	@es_extended/locale.lua:10: in function '_'
	@es_extended/locale.lua:20: in function '_U'
	@stasiek_selldrugs/server/main.lua:162: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Error running system event handling function for resource stasiek_selldrugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/locale.lua:10: attempt to concatenate a nil value (local 'str')
stack traceback:
	@es_extended/locale.lua:10: in function '_'
	@es_extended/locale.lua:20: in function '_U'
	@stasiek_selldrugs/server/main.lua:162: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Error running system event handling function for resource stasiek_selldrugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/locale.lua:10: attempt to concatenate a nil value (local 'str')
stack traceback:
	@es_extended/locale.lua:10: in function '_'
	@es_extended/locale.lua:20: in function '_U'
	@stasiek_selldrugs/server/main.lua:162: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Error running system event handling function for resource stasiek_selldrugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/locale.lua:10: attempt to concatenate a nil value (local 'str')
stack traceback:
	@es_extended/locale.lua:10: in function '_'
	@es_extended/locale.lua:20: in function '_U'
	@stasiek_selldrugs/server/main.lua:162: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Sending heartbeat to live-internal.fivem.net:30110
Sending heartbeat to live-internal.fivem.net:30110
Error running system event handling function for resource stasiek_selldrugs: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: @es_extended/locale.lua:10: attempt to concatenate a nil value (local 'str')
stack traceback:
	@es_extended/locale.lua:10: in function '_'
	@es_extended/locale.lua:20: in function '_U'
	@stasiek_selldrugs/server/main.lua:162: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Sending heartbeat to live-internal.fivem.net:30110

**Comment by Bevilh2o** [comment]
This error is related to line 162 of server/main.lua

"TriggerClientEvent('esx:showNotification', _source, _U('you_have_sold') .. '~b~'..x..'~w~' .. _U(drugtype) .. blackMoney .. '$')"

"_U(drugtype)" is causing the error.
