### ISSUE TITLE
Attempt to index a nil value

### ISSUE THREAD

**Issue by Kuhicop** [xxxstasiek/stasiek_selldrugs#16]
I'm getting this error:

![image](https://user-images.githubusercontent.com/27239965/71563250-9746a980-2a8c-11ea-8cda-91ae44e377bc.png)

This is the line: `local weedqty = xPlayer.getInventoryItem('weed_pooch').count`

**Comment by analski** [comment]
m2

**Comment by tomyzz** [comment]
m2

**Comment by Kuhicop** [comment]
```
local weedqty = xPlayer.getInventoryItem('weed_pooch')

if weedqty ~= nil then
    weedqty = weedqty.count
end

```
That's solving the issue
